# Generated by Django 4.1.1 on 2022-11-01 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flickr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('pk', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='flickr',
            name='album',
            field=models.ManyToManyField(blank=True, to='flickr.album'),
        ),
    ]
