# Generated by Django 4.1.1 on 2022-11-02 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flickr', '0002_album_flickr_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
