# Generated by Django 4.1.1 on 2022-11-15 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flickr', '0003_album_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='pk',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='flickr',
            old_name='pk',
            new_name='id',
        ),
    ]
