# Generated by Django 4.1.1 on 2022-12-01 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flickr', '0004_rename_pk_album_id_rename_pk_flickr_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
