# Generated by Django 4.1.1 on 2022-12-01 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flickr', '0005_alter_album_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flickr',
            name='album',
        ),
    ]
