# Generated by Django 4.1.1 on 2022-12-01 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flickr', '0006_remove_flickr_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='photos',
            field=models.ManyToManyField(blank=True, to='flickr.flickr'),
        ),
    ]
