# Generated by Django 4.1.1 on 2022-12-09 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flickr', '0007_album_photos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flickr',
            options={'ordering': ['date_taken_obj']},
        ),
    ]
