# Generated by Django 4.1.1 on 2022-09-29 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Era',
            fields=[
                ('pk', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('pk', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('caption', models.CharField(blank=True, max_length=100, null=True)),
                ('credit', models.CharField(blank=True, max_length=100, null=True)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('alt', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('link_target', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('pk', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(blank=True, max_length=200, null=True)),
                ('text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('pk', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('group', models.CharField(blank=True, max_length=50, null=True)),
                ('display_date', models.CharField(blank=True, max_length=50, null=True)),
                ('background_color', models.CharField(blank=True, max_length=50, null=True)),
                ('autolink', models.BooleanField(blank=True, default=True, null=True)),
                ('unique_id', models.CharField(blank=True, max_length=100, null=True)),
                ('media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timelinejs.media')),
                ('text', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timelinejs.text')),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('pk', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('scale', models.CharField(default='human', max_length=100)),
                ('era', models.ManyToManyField(to='timelinejs.era')),
                ('events', models.ManyToManyField(to='timelinejs.slide')),
            ],
        ),
        migrations.AddField(
            model_name='era',
            name='text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timelinejs.text'),
        ),
    ]
