# Generated by Django 4.1.1 on 2022-09-29 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelinejs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
