# Generated by Django 4.1.1 on 2022-09-30 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timelinejs', '0002_alter_events_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_title', to='timelinejs.slide'),
        ),
    ]
