# Generated by Django 4.1.1 on 2022-10-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelinejs', '0003_alter_events_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
