# Generated by Django 4.1.1 on 2022-11-09 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timelinejs', '0004_alter_media_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timelinejs.media'),
        ),
    ]
