# Generated by Django 4.1.1 on 2022-11-15 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timelinejs', '0005_alter_slide_media'),
    ]

    operations = [
        migrations.RenameField(
            model_name='era',
            old_name='pk',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='pk',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='media',
            old_name='pk',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='slide',
            old_name='pk',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='text',
            old_name='pk',
            new_name='id',
        ),
    ]
