# Generated by Django 4.1.1 on 2022-09-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.IntegerField()),
                ('lft', models.IntegerField()),
                ('rgt', models.IntegerField()),
                ('item', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
