# Generated by Django 4.1.1 on 2022-09-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='item',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
