# Generated by Django 4.1.1 on 2022-09-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0002_alter_library_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='parent',
            field=models.IntegerField(default=True, null=True),
        ),
    ]
