# Generated by Django 4.1.1 on 2022-09-23 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0005_typedocument_library_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='is_true',
            field=models.BooleanField(null=True),
        ),
    ]
