# Generated by Django 4.1.1 on 2022-11-15 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0007_rename_library_documentitem'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='documentitem',
        #     old_name='pk',
        #     new_name='id',
        # ),
        # migrations.RenameField(
        #     model_name='typedocument',
        #     old_name='pk',
        #     new_name='id',
        # ),
        # migrations.AlterField(
        #     model_name='documentitem',
        #     name='is_true',
        #     field=models.BooleanField(default=False, null=True),
        # ),
        # migrations.AlterField(
        #     model_name='documentitem',
        #     name='parent',
        #     field=models.IntegerField(null=True),
        # ),
        migrations.CreateModel(
            name='DocumentText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('document_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliotheque.documentitem')),
            ],
        ),
    ]
