# Generated by Django 4.1.1 on 2022-11-16 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0008_rename_pk_documentitem_id_rename_pk_typedocument_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentitem',
            name='is_true',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
