# Generated by Django 4.1.1 on 2022-11-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0009_alter_documentitem_is_true'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentitem',
            old_name='pk',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='typedocument',
            old_name='pk',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='documentitem',
            name='parent',
            field=models.IntegerField(null=True),
        ),
    ]
