# Generated by Django 4.1.1 on 2022-12-09 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0011_alter_documenttext_document_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documenttext',
            name='id',
        ),
        migrations.AlterField(
            model_name='documenttext',
            name='document_section',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bibliotheque.documentitem'),
        ),
    ]
