# Generated by Django 4.1.1 on 2022-12-09 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0012_remove_documenttext_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentitem',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentitem',
            name='desc',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bibliotheque.typedocument'),
        ),
    ]
