# Generated by Django 4.1.1 on 2022-09-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotosLibrary',
            fields=[
                ('pk', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('file', models.ImageField(blank=True, null=True, upload_to='')),
                ('desc', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
