# Generated by Django 4.1.1 on 2022-09-26 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_alter_photoslibrary_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photoslibrary',
            old_name='desc',
            new_name='caption',
        ),
    ]
