# Generated by Django 4.1.1 on 2022-09-26 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_rename_desc_photoslibrary_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoslibrary',
            name='group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='photoslibrary',
            name='caption',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
