# Generated by Django 4.1.1 on 2022-09-26 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_photoslibrary_group_alter_photoslibrary_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoslibrary',
            name='headline',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
