# Generated by Django 4.1.1 on 2022-09-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_photoslibrary_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineEra',
            fields=[
                ('pk', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('text_title', models.CharField(max_length=100)),
                ('text_text', models.CharField(max_length=100)),
            ],
        ),
    ]
