# Generated by Django 4.1.1 on 2022-09-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0007_timelineera'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timelineera',
            old_name='text_title',
            new_name='text_headline',
        ),
        migrations.AlterField(
            model_name='timelineera',
            name='text_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
