# Generated by Django 4.1.1 on 2022-11-15 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0008_rename_text_title_timelineera_text_headline_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photoslibrary',
            old_name='pk',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='timelineera',
            old_name='pk',
            new_name='id',
        ),
    ]
