# Generated by Django 4.1.1 on 2024-01-24 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0009_rename_pk_photoslibrary_id_rename_pk_timelineera_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlikrPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('source', models.URLField(unique=True)),
                ('url', models.URLField()),
                ('media', models.CharField(max_length=255)),
                ('caption', models.CharField(blank=True, max_length=100, null=True)),
                ('group', models.CharField(blank=True, max_length=100, null=True)),
                ('headline', models.CharField(blank=True, max_length=100, null=True)),
                ('text', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
