# Generated by Django 4.1.1 on 2024-01-24 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0010_flikrphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='flikrphoto',
            name='date_taken',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
