# Generated by Django 4.1.1 on 2024-01-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0011_flikrphoto_date_taken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flikrphoto',
            options={'ordering': ['date_taken']},
        ),
        migrations.AddField(
            model_name='flikrphoto',
            name='serie',
            field=models.SmallIntegerField(default=None, null=True),
        ),
    ]
