# Generated by Django 4.1.1 on 2024-02-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0015_alter_flikrphoto_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('photos', models.ManyToManyField(blank=True, to='photos.flikrphoto')),
            ],
        ),
    ]
