# Generated by Django 4.1.1 on 2024-03-05 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0016_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimaryArchivePhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('path', models.CharField(max_length=255)),
            ],
        ),
    ]
